name: TARA-Analysis
channels:
  - etetoolkit
  - conda-forge
dependencies:
  - python=3.8
  - nodejs
  - ete3
  - pip
  - npm
  - pip:
      - -r requirements.txt
  - npm:
      - react-plotly.js plotly.js @types/react-plotly.js
