name: TARA-Analysis
channels:
  - etetoolkit
  - conda-forge
  - anaconda
dependencies:
  - python~=3.10
  - pip
  - pyqt~=5.15.7
  - pip:
      - plumbum~=1.8.2
      - numpy~=1.25.0
      - pandas~=2.0.2
      - seaborn~=0.12.2
      - matplotlib~=3.7.1
      - altair~=5.0.1
      - streamlit~=1.23.1
      - protobuf~=3.20.3
      - dash~=2.11.0
      - jupyter~=1.0.0
      - biopython~=1.81
      - pylint~=2.17.4
      - scipy~=1.10.1
      - scikit-learn~=1.2.2
      - ete3~=3.1.3
      - .
